/* Past-paper items — wording from CCEA GCSE Digital Technology Unit 1 papers, answers from the CCEA mark schemes.
   Every item maps to a row in S1 Software/SOURCE_MAP.md. Shared by the topic activities and the Exam Arena. */
const PP={
/* ---------- operating system / system software ---------- */
os2018b1:{type:'pick',src:'PP 2018 Q5(b)(i)',ref:'2018 Q5(b)(i) · 2 marks',need:2,
  q:'The system software on a laptop manages resources. Apart from allocating memory, list two other resources that are managed by system software.',
  options:[{text:'Storage',ok:true},{text:'Processor time',ok:true},{text:'Hardware',ok:true},{text:'Software',ok:true},{text:'Memory',ok:false},{text:'Defragmenting',ok:false},{text:'Booting',ok:false}],
  feedback:'Mark scheme, any two: storage (devices) / (data) storage; processor time; hardware; software. Memory does not count, because the question says "apart from allocating memory".'},
os2018b2:{type:'order',src:'PP 2018 Q5(b)(ii)',ref:'2018 Q5(b)(ii) · 3 marks',
  q:'Explain how memory is allocated by system software when a user wants to access data held on a hard disk. Click the three steps in the correct order.',
  steps:['A free space in memory (RAM) is located','The free space is allocated to the data/program','The program/data is transferred back out of main memory when it is no longer required'],
  feedback:'These are the three mark-scheme points, one mark each: locate free space → allocate it → transfer back out when no longer required.'},
os2023b:{type:'pick',src:'PP 2023 Q5(b)',ref:'2023 Q5(b) · 2 marks',need:2,
  q:'List two resources managed by the operating system in a computer system.',
  options:[{text:'Memory (RAM)',ok:true},{text:'Storage',ok:true},{text:'Processing time',ok:true},{text:'Peripherals',ok:true},{text:'Billing systems',ok:false},{text:'Booting',ok:false}],
  feedback:'Mark scheme accepts: memory / RAM allocation; storage; processing time / task scheduling; peripherals. Any two.'},
os2024:{type:'match',src:'PP 2024 Q10',ref:'2024 Q10 (part) · 3 marks',
  q:'Choose the term that best matches each definition.',
  pairs:[{term:'Operating System',def:'A computer program that provides the instructions that enable the computer hardware to work'},
         {term:'Graphical User Interface',def:'Used to interact with a computer through icons and menus'},
         {term:'Backup',def:'A method used to keep another copy of the original data'}],
  feedback:'Operating System, Graphical User Interface and Backup — straight from the 2024 mark scheme.'},
os2025a:{type:'mcq',src:'PP 2025 Q4(a)',ref:'2025 Q4(a) · 1 mark',
  q:'What is the name given to the sequence of loading an operating system into RAM when a computer is turned on?',
  options:['Booting (booting up)','Defragmenting','Task scheduling','Backing up'],answer:0,
  feedback:'Mark scheme: booting / booting up / bootup / start up sequence. Writing just "boot" does not get the mark.'},
os2025b:{type:'fill',src:'PP 2025 Q4(b)',ref:'2025 Q4(b) · 4 marks',
  q:'Complete the sentences below using the words supplied. (Not all words will be used.)',
  bank:['WORD','RESOURCES','INTERFACE','MANAGE','SOFTWARE'],
  text:'Operating systems are [[SOFTWARE]] that [[MANAGE]] computer hardware and software [[RESOURCES]]. An operating system provides the user with a working [[INTERFACE]].',
  feedback:'SOFTWARE, MANAGE, RESOURCES, INTERFACE. WORD is the one left over.'},
/* ---------- modes of processing ---------- */
mode2018c:{type:'fill',src:'PP 2018 Q5(c)',ref:'2018 Q5(c) · 4 marks',
  q:'Complete the paragraph, using the phrases listed, to explain the modes of processing.',
  bank:['airline booking systems','batch processing','real-time processing','billing systems'],
  text:'Collecting groups of similar data over time and processing the data together is called [[batch processing]]. This type of processing is suitable for [[billing systems]]. Processing data immediately as it is collected is called [[real-time processing]]. This type of processing is suitable for [[airline booking systems]].',
  feedback:'Batch processing → billing systems. Real-time processing → airline booking systems.'},
mode2022d:{type:'mcq',src:'PP 2022 Q1(d)',ref:'2022 Q1(d) · 1 mark',keepOrder:true,
  q:'Select the statement which is correct about real-time processing.',
  options:['Real-time processing involves collecting data together and processing it at a later time.',
           'Real-time processing is used for online booking systems and involves processing data as soon as it is entered into the system.',
           'Real-time processing is used for online booking systems and involves collecting data and processing it at a later time.',
           'Real-time processing is used to produce consumer bills like electricity bills and involves processing data as soon as it is entered into the system.'],answer:1,
  feedback:'Answer B. Online booking = real-time, and the data is processed as soon as it is entered. "Later" and "bills" both belong to batch.'},
mode2023c1:{type:'classify',src:'PP 2023 Q5(c)',ref:'2023 Q5(c) · 1 mark',
  text:'"Data is processed immediately on collection"',
  choices:[{key:'mt',label:'Multi-tasking'},{key:'rt',label:'Real-time'},{key:'mu',label:'Multi-user'}],answer:'rt',
  feedback:'Real-time: data is processed immediately on collection.'},
mode2023c2:{type:'classify',src:'PP 2023 Q5(c)',ref:'2023 Q5(c) · 1 mark',
  text:'"Manages the sharing of CPU time and resources needed by many users"',
  choices:[{key:'mt',label:'Multi-tasking'},{key:'rt',label:'Real-time'},{key:'mu',label:'Multi-user'}],answer:'mu',
  feedback:'Multi-user: many users share the CPU time and resources.'},
mode2023q12a:{type:'mcq',src:'PP 2023 Q12(a)',ref:'2023 Q12(a) · 1 mark',keepOrder:true,
  q:'Which statement best describes <b>batch</b> processing?',
  options:['Processing data fast enough to influence the behaviour of the next input','Processing that enables several users to use the system at once','Processing data all together during processor downtime'],answer:2,
  feedback:'Batch = processing data all together during processor downtime. The first statement is real-time and the second is multi-user.'},
/* ---------- utilities ---------- */
util2018q12:{type:'mcq',src:'PP 2018 Q12',ref:'2018 Q12 (part) · 1 mark',keepOrder:true,
  q:'Choose the term that best matches this definition: "A utility that rearranges data on a disk so that files are stored together in blocks, meaning they can be read more quickly."',
  options:['BLUETOOTH','DEFRAGMENTING','SWITCH','TASK SCHEDULING','PROGRAM COUNTER','ROUTER','Wi-Fi','MEMORY DATA REGISTER'],answer:1,
  feedback:'DEFRAGMENTING. Task scheduling is the trap: it is a utility too, but it shares out processor time.'},
util2019defrag:{type:'pick',src:'PP 2019 Q5(b)',ref:'2019 Q5(b) part 1 · 2 marks',need:2,
  q:'What is the function of <b>disk defragmenting</b>? Choose two mark-scheme points.',
  options:[{text:'Rearranges data so files are stored in blocks together, with free storage space together',ok:true},{text:'Speeds up the time to access data',ok:true},{text:'Uses time slicing to get maximum use of the processor',ok:false},{text:'Makes a copy of data in case the original is lost',ok:false}],
  feedback:'Mark scheme: rearranges data / stores files in blocks together / free storage space [1]; speeds up the time to access data [1].'},
util2019task:{type:'pick',src:'PP 2019 Q5(b)',ref:'2019 Q5(b) part 2 · 2 marks',need:2,
  q:'What is the function of <b>task scheduling</b>? Choose two mark-scheme points.',
  options:[{text:'Uses time slicing',ok:true},{text:'Gets maximum use of the processor',ok:true},{text:'Creates the appearance of no interruptions',ok:true},{text:'Rearranges data so files are stored together',ok:false},{text:'Collects groups of similar data to process later',ok:false}],
  feedback:'Mark scheme: time slicing [1] to get maximum use of the processor [1]. Another answer that gets the marks: it runs tasks automatically at a set time [1], with an example such as a backup schedule, a virus check schedule or update scheduling [1].'},
util2022i:{type:'mcq',src:'PP 2022 Q1(i)',ref:'2022 Q1(i) · 1 mark',keepOrder:true,
  q:'Select the correct definition for the term backup.',
  options:['A file which has been restored following damage to the original.','A copy of an original file used to restore data.','An encrypted version of a file.','A record of outdated files stored in another location.'],answer:1,
  feedback:'Answer B: a copy of an original file used to restore data.'},
util2022b:{type:'pick',src:'PP 2022 Q5(b)',ref:'2022 Q5(b) · 2 marks',need:2,
  q:'John uses utility programs to maintain his computer system. List two utility programs used for this purpose.',
  options:[{text:'Disc defragmenter',ok:true},{text:'Task scheduling',ok:true},{text:'Backup',ok:true},{text:'Anti-virus',ok:true},{text:'Word processor',ok:false},{text:'Payroll system',ok:false}],
  feedback:'Mark scheme accepts: disc defragmenter / clean-up; task scheduling / Task Manager; backup; restore; anti-virus; firewall. A word processor is application software.'},
util2023d:{type:'mcq',src:'PP 2023 Q5(d)',ref:'2023 Q5(d) · 1 mark',
  q:'Which software group does defragmentation belong to?',
  options:['Utility software','Application software','Booting','Batch processing'],answer:0,
  feedback:'Mark scheme: utility (programs / software / application).'},
util2023b:{type:'pick',src:'PP 2023 Q12(b)',ref:'2023 Q12(b) · 2 marks',need:2,
  q:'Chen Chi is learning about backing up his computer files. Explain the term backup. Choose two correct points.',
  options:[{text:'A backup is a copy of data or files',ok:true},{text:'Backups are made to ensure no data is lost by becoming corrupt, accidentally overwritten or deleted',ok:true},{text:'Backups are often made on separate storage drives or on a different server',ok:true},{text:'A backup is an encrypted version of a file',ok:false},{text:'A backup rearranges files so they can be read more quickly',ok:false}],
  feedback:'Mark scheme, any two: a copy of data or files; made so no data is lost by becoming corrupt, accidentally overwritten or deleted; often made on separate storage drives or a different server.'},
util2025d:{type:'mcq',src:'PP 2025 Q1(d)',ref:'2025 Q1(d) · 1 mark',keepOrder:true,
  q:'Which of the following tasks are commonly carried out by utility applications?',
  options:['Sending and receiving emails','Creating and editing documents','Playing multimedia files','Backup and restoring data'],answer:3,
  feedback:'Answer D: backup and restoring data. Emails, documents and multimedia are all done by application software.'},
/* ---------- anti-virus ---------- */
av2025c:{type:'mcq',src:'PP 2025 Q1(c)',ref:'2025 Q1(c) · 1 mark',keepOrder:true,
  q:'Which of the following statements best describes the role of antivirus software?',
  options:['Prevents hardware malfunctions','Protects against malicious attacks','Enhances internet connectivity','Provides advanced graphics and multimedia capabilities'],answer:1,
  feedback:'Answer B: protects against malicious attacks.'}
};
